"""Add status column to tests table

Revision ID: 1901c3ae6f4b
Revises: a2595c7a631e
Create Date: 2024-10-12 16:49:25.181281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1901c3ae6f4b'
down_revision: Union[str, None] = 'a2595c7a631e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'status')
    # ### end Alembic commands ###
