"""Add selected_llms column to Test model

Revision ID: c07987c701a7
Revises: c9b346bdc777
Create Date: 2024-10-12 15:33:47.663990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07987c701a7'
down_revision: Union[str, None] = 'c9b346bdc777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('selected_llms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'selected_llms')
    # ### end Alembic commands ###
