"""Update Test model with cascade and timezone-aware datetime

Revision ID: f538328c57e4
Revises: 1901c3ae6f4b
Create Date: 2024-10-12 16:51:40.126574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f538328c57e4'
down_revision: Union[str, None] = '1901c3ae6f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
